### Sol 1 Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region.


In [3]:
## Sol 1
import numpy as np

SalesA= [10, 15, 12, 8, 14]
SalesB= [18, 20, 16, 22, 25]

print("Mean Sales of Region A",np.mean(SalesA),"Mean Sales of Region B",np.mean(SalesB))



Mean Sales of Region A 11.8 Mean Sales of Region B 20.2


### Sol 2 Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.


In [4]:
## Sol 2

from statistics import mode

response=[4, 5, 2, 3, 5, 4, 3, 2, 4, 5]

x=(mode(response))

print("Mode of Survey Response",x)

Mode of Survey Response 4


### Sol 3 Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [6]:
## Sol 3

DepartmentA=[5000, 6000, 5500, 7000]
DepartmentB=[4500, 5500, 5800, 6000, 5200]

print("Median Sales of Region A",np.median(DepartmentA),"Median Sales of Region B",np.median(DepartmentB))

Median Sales of Region A 5750.0 Median Sales of Region B 5500.0


### Sol 4 Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [7]:
## Sol 4

StockPrices= [25.5, 24.8, 26.1, 25.3, 24.9]

print("Range of Stocks",np.max(StockPrices)-np.min(StockPrices))

Range of Stocks 1.3000000000000007


### Sol 5 Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [12]:
## Sol 5 

import scipy.stats as stats

GroupA=[85, 90, 92, 88, 91]
GroupB=[82, 88, 90, 86, 87]

stats.ttest_ind(a=GroupA, b=GroupB, equal_var=True)

print(x.statistic)
print(x.pvalue)



1.4312528946642733
0.19023970239078333


### Sol 6 Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [14]:
## Sol 6 

Advertisement = 1000*[10, 15, 12, 8, 14]
Sales = 1000* [25, 30, 28, 20, 26]

print(np.corrcoef(Advertisement, Sales))

[[1.         0.87575114]
 [0.87575114 1.        ]]


### Sol 7 Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights.


In [15]:
## Sol 7 

survey=[160, 170, 165, 155, 175, 180, 170]

print("Standard Deviation of survey",np.std(survey))

Standard Deviation of survey 7.953949089757174


### Sol 8 Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [16]:
## Sol 8 

import statsmodels.api as sm


EmployeeTenure = [2, 3, 5, 4, 6, 2, 4]
JobSatisfaction =[7, 8, 6, 9, 5, 7, 6]

model = sm.OLS(JobSatisfaction,EmployeeTenure)

results = model.fit()
## Predict for Tenure of 5 Years
results.predict([5])




array([7.81818182])

### Sol 9 Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
   Medication B: [15, 17, 16, 14, 18]
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


In [17]:
## Sol 9 
from scipy.stats import f_oneway

MedicationA=[10, 12, 14, 11, 13]
MedicationB=[15, 17, 16, 14, 18]

f_oneway(MedicationA,MedicationB)

## Reject null hypotghesis at 0.05 significance level there exits a difference

F_onewayResult(statistic=16.0, pvalue=0.003949772803445326)

### Sol 10 Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings.


In [18]:
## Sol 10

ratings = [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]

print("75th Percentile of ",np.percentile(ratings,75))

75th Percentile of  8.75


### Sol 11 Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [20]:
## Sol 11
'''
Ho: Means are same as 10
Ha: Means are different from 10
'''
from scipy.stats import ttest_1samp

sample = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]


tset, pval = ttest_1samp(sample, 10)

print(tset, pval)

#No there is no significant difference from 10 we failed to reject null hypotheis at 0.05

1.5126584522688367 0.19077595151110102


### Sol 12 Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [21]:
## Sol 12

from scipy.stats import chisquare

DesignA=[100, 120, 110, 90, 95]
DesignB=[80, 85, 90, 95, 100]

obs = np.array([DesignA, DesignB]).T

chisquare(obs)

Power_divergenceResult(statistic=array([5.63106796, 2.77777778]), pvalue=array([0.22844647, 0.59567472]))

### Sol 13 Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [22]:
## Sol 13

Score =  [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]

import scipy.stats as st
  
# create 95% confidence interval
# for population mean weight
st.norm.interval(alpha=0.90,
                 loc=np.mean(Score),
                 scale=st.sem(Score))

/var/folders/6d/qpxd8v516bdb8gj9wxny9xs40000gp/T/ipykernel_20383/2075700353.py:9: DeprecationWarning: Use of keyword argument 'alpha' for method 'interval' is deprecated and wil be removed in SciPy 1.11.0. Use first positional argument or keyword argument 'confidence' instead.
  st.norm.interval(alpha=0.90,


(7.277268467352362, 8.522731532647638)

### Sol 14 Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperature.


In [34]:
## Sol 14 

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

Temperature= np.array([20, 22, 23, 19, 21]).reshape(-1,1)
Performance= np.array([8, 7, 9, 6, 8]).reshape(-1,1)

lr.fit(Temperature,Performance)
print(lr.score(Temperature,Performance))
lr.intercept_

0.4807692307692307


array([-2.9])

### Sol 15 Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
    Group A: [4, 3, 5, 2, 4]
    Group B: [3, 2, 4, 3, 3]
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


In [36]:
### Sol 15 

from scipy.stats import mannwhitneyu

GroupA=[4, 3, 5, 2, 4]
GroupB=[3, 2, 4, 3, 3]

U1, p = mannwhitneyu(GroupA,GroupB,method="exact")
print(U1)
print(p)

17.0
0.42063492063492064


### Sol 16  Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [37]:
## Sol 16 

ages =  [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]

stats.iqr(ages, interpolation = 'midpoint')

20.0

### Sol 17 Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [39]:
## Sol 17 

AlgorithmA=[0.85, 0.80, 0.82, 0.87, 0.83]
AlgorithmB=[0.78, 0.82, 0.84, 0.80, 0.79]
AlgorithmC=[0.90, 0.88, 0.89, 0.86, 0.87]

stats.kruskal(AlgorithmA,AlgorithmB,AlgorithmC)


KruskalResult(statistic=9.696947935368053, pvalue=0.007840333026249539)

### Sol 18 Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    Sales: [100, 80, 90, 110, 95]
    Perform a simple linear regression to predict

 sales based on price.


In [42]:
## Sol 18 

Price=np.array([10, 15, 12, 8, 14]).reshape(-1,1)
Sales=np.array([100, 80, 90, 110, 95]).reshape(-1,1)

lr.fit(Sales,Price)
print(lr.score(Sales,Price))
lr.intercept_


0.8064024390243903


array([33.65])

### Sol 19 Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.


In [43]:
## Sol 19 

from scipy.stats import sem

data=  [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]

sem(data)

0.30550504633038933

### Sol 20 Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.

In [44]:
### Sol 20 

Advertisement = np.array(1000*[10, 15, 12, 8, 14]).reshape(-1,1)
Sales = np.array(1000* [25, 30, 28, 20, 26]).reshape(-1,1)

lr.fit(Advertisement,Sales)
print(lr.score(Advertisement,Sales))
lr.intercept_

0.7669400549639299


array([12.20121951])